package com.briup.apps.bean;

public class ArrangeTime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangetime.id
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangetime.date
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    private String date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangetime.user_id
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangetime.coach_id
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    private Integer coachId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangetime.car_id
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    private Integer carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangetime.status
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangetime.id
     *
     * @return the value of arrangetime.id
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangetime.id
     *
     * @param id the value for arrangetime.id
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangetime.date
     *
     * @return the value of arrangetime.date
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangetime.date
     *
     * @param date the value for arrangetime.date
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangetime.user_id
     *
     * @return the value of arrangetime.user_id
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangetime.user_id
     *
     * @param userId the value for arrangetime.user_id
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangetime.coach_id
     *
     * @return the value of arrangetime.coach_id
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    public Integer getCoachId() {
        return coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangetime.coach_id
     *
     * @param coachId the value for arrangetime.coach_id
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    public void setCoachId(Integer coachId) {
        this.coachId = coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangetime.car_id
     *
     * @return the value of arrangetime.car_id
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangetime.car_id
     *
     * @param carId the value for arrangetime.car_id
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangetime.status
     *
     * @return the value of arrangetime.status
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangetime.status
     *
     * @param status the value for arrangetime.status
     *
     * @mbg.generated Tue May 05 10:38:35 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}