package com.briup.apps.bean;

public class ArrangeTime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangetime.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangetime.startTime
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Long starttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangetime.endTime
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Long endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangetime.user_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangetime.coach_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer coachId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangetime.car_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column arrangetime.status
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangetime.id
     *
     * @return the value of arrangetime.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangetime.id
     *
     * @param id the value for arrangetime.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangetime.startTime
     *
     * @return the value of arrangetime.startTime
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Long getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangetime.startTime
     *
     * @param starttime the value for arrangetime.startTime
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setStarttime(Long starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangetime.endTime
     *
     * @return the value of arrangetime.endTime
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Long getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangetime.endTime
     *
     * @param endtime the value for arrangetime.endTime
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setEndtime(Long endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangetime.user_id
     *
     * @return the value of arrangetime.user_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangetime.user_id
     *
     * @param userId the value for arrangetime.user_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangetime.coach_id
     *
     * @return the value of arrangetime.coach_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getCoachId() {
        return coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangetime.coach_id
     *
     * @param coachId the value for arrangetime.coach_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setCoachId(Integer coachId) {
        this.coachId = coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangetime.car_id
     *
     * @return the value of arrangetime.car_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangetime.car_id
     *
     * @param carId the value for arrangetime.car_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column arrangetime.status
     *
     * @return the value of arrangetime.status
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column arrangetime.status
     *
     * @param status the value for arrangetime.status
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}