package com.briup.apps.bean;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.car_number
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String carNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.type
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column car.coach_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer coachId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.id
     *
     * @return the value of car.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.id
     *
     * @param id the value for car.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.car_number
     *
     * @return the value of car.car_number
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.car_number
     *
     * @param carNumber the value for car.car_number
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber == null ? null : carNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.type
     *
     * @return the value of car.type
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.type
     *
     * @param type the value for car.type
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column car.coach_id
     *
     * @return the value of car.coach_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getCoachId() {
        return coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column car.coach_id
     *
     * @param coachId the value for car.coach_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setCoachId(Integer coachId) {
        this.coachId = coachId;
    }
}