package com.briup.apps.bean;

public class Coach_Accept {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_accept.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_accept.name
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_accept.age
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_accept.gender
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_accept.charges
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer charges;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_accept.password
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach_accept.role_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_accept.id
     *
     * @return the value of coach_accept.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_accept.id
     *
     * @param id the value for coach_accept.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_accept.name
     *
     * @return the value of coach_accept.name
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_accept.name
     *
     * @param name the value for coach_accept.name
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_accept.age
     *
     * @return the value of coach_accept.age
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_accept.age
     *
     * @param age the value for coach_accept.age
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_accept.gender
     *
     * @return the value of coach_accept.gender
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_accept.gender
     *
     * @param gender the value for coach_accept.gender
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_accept.charges
     *
     * @return the value of coach_accept.charges
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getCharges() {
        return charges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_accept.charges
     *
     * @param charges the value for coach_accept.charges
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setCharges(Integer charges) {
        this.charges = charges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_accept.password
     *
     * @return the value of coach_accept.password
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_accept.password
     *
     * @param password the value for coach_accept.password
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach_accept.role_id
     *
     * @return the value of coach_accept.role_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach_accept.role_id
     *
     * @param roleId the value for coach_accept.role_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}