package com.briup.apps.bean;

public class Coach {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.name
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.age
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.gender
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.charges
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer charges;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.status
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.password
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.car_Number
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String carNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coach.car_type
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String carType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.id
     *
     * @return the value of coach.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.id
     *
     * @param id the value for coach.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.name
     *
     * @return the value of coach.name
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.name
     *
     * @param name the value for coach.name
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.age
     *
     * @return the value of coach.age
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.age
     *
     * @param age the value for coach.age
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.gender
     *
     * @return the value of coach.gender
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.gender
     *
     * @param gender the value for coach.gender
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.charges
     *
     * @return the value of coach.charges
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getCharges() {
        return charges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.charges
     *
     * @param charges the value for coach.charges
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setCharges(Integer charges) {
        this.charges = charges;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.status
     *
     * @return the value of coach.status
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.status
     *
     * @param status the value for coach.status
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.password
     *
     * @return the value of coach.password
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.password
     *
     * @param password the value for coach.password
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.car_Number
     *
     * @return the value of coach.car_Number
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getCarNumber() {
        return carNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.car_Number
     *
     * @param carNumber the value for coach.car_Number
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setCarNumber(String carNumber) {
        this.carNumber = carNumber == null ? null : carNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coach.car_type
     *
     * @return the value of coach.car_type
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coach.car_type
     *
     * @param carType the value for coach.car_type
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }
}