package com.briup.apps.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.name
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.age
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.gender
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.coach_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer coachId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.phoneNum
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String phonenum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.role_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.age
     *
     * @return the value of users.age
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.age
     *
     * @param age the value for users.age
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.gender
     *
     * @return the value of users.gender
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.gender
     *
     * @param gender the value for users.gender
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.coach_id
     *
     * @return the value of users.coach_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getCoachId() {
        return coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.coach_id
     *
     * @param coachId the value for users.coach_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setCoachId(Integer coachId) {
        this.coachId = coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.phoneNum
     *
     * @return the value of users.phoneNum
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getPhonenum() {
        return phonenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.phoneNum
     *
     * @param phonenum the value for users.phoneNum
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setPhonenum(String phonenum) {
        this.phonenum = phonenum == null ? null : phonenum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.role_id
     *
     * @return the value of users.role_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.role_id
     *
     * @param roleId the value for users.role_id
     *
     * @mbg.generated Sat Mar 28 22:46:04 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}